config/routes.rb
Rails.application.routes.draw do
  resources :subscriptions, only: [:index, :new, :create]
  resources :home, only: :index
  root to: "home#index"
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/subscription.rb
class Subscription < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def notification_alert(type="", title="", text="")
    return {
      position: 'center',
      type: type,
      title: title,
      text: text,
      showConfirmButton: true,
    }
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: [:show, :edit, :update, :destroy]

  # GET /subscriptions
  # GET /subscriptions.json
  def index
    @subscriptions = Subscription.all
  end

  # GET /subscriptions/1
  # GET /subscriptions/1.json
  def show
  end

  # GET /subscriptions/new
  def new
    @subscription = Subscription.new
  end

  # GET /subscriptions/1/edit
  def edit
  end

  # POST /subscriptions
  # POST /subscriptions.json
  def create
    @subscription = Subscription.new(subscription_params)

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to home_index_url, 
          notice: notification_alert('success', 
                                     'Cadastro efetuado com sucesso!',
                                     "Nossos serviços ainda estão indisponíveis. Mas, fique tranquilo. Assim que possível, entraremos em contato com você, e lhe informaremos sobre as novidades e todas as vantagens de nosso produto.") }
        format.json { render :show, status: :created, location: @subscription }
      else
        format.html { render :new }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscriptions/1
  # PATCH/PUT /subscriptions/1.json
  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to @subscription, notice: 'Subscription was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscription }
      else
        format.html { render :edit }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription.destroy
    respond_to do |format|
      format.html { redirect_to subscriptions_url, notice: 'Subscription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscription_params
      params.require(:subscription).permit(:name, :email, :initial_date, :final_date, :smallbag_quantity, :mediumbag_quantity, :bigbag_quantity, :value, :phone_number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/application/_footer.html.erb
<!-- start footer Area -->		
<footer class="footer-area">
  <div class="container">
    <div class="row footer-bottom d-flex justify-content-between">
      <p class="col-lg-8 col-sm-12 footer-text m-0 text-white">
        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | Made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">WanderBag!</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
      </p>
      <div class="col-lg-4 col-sm-12 footer-social">
        <a href="#"><i class="fa fa-facebook"></i></a>
        <a href="#"><i class="fa fa-twitter"></i></a>
        <a href="#"><i class="fa fa-dribbble"></i></a>
        <a href="#"><i class="fa fa-behance"></i></a>
      </div>
    </div>
  </div>
</footer>
<!-- End footer Area -->		

app/views/application/_header.html.erb
<header id="header" id="home">
  <div class="container">
    <div class="row align-items-center justify-content-between d-flex">
      <div id="logo">
        <a href="/"><img src="/template/img/logo.png" alt="" title="" /></a>
      </div>
      <nav id="nav-menu-container">
        <ul class="nav-menu">
          <li class="menu-active">
              <%= link_to 'Home', home_index_url(:anchor => "home"), class: "genric-btn primary-border small" %>
          </li>
          <li>
              <%= link_to 'Serviços', home_index_url(:anchor => "offer"), class: "genric-btn primary-border small" %>
          </li>
          <li>
              <%= link_to 'Sobre', home_index_url(:anchor => "about"), class: "genric-btn primary-border small" %>
          </li>
          <li>
              <%= link_to 'WanderBags!', home_index_url(:anchor => "wanderbags"), class: "genric-btn primary-border small" %>
          </li>
          <li>
              <%= link_to 'Planos', home_index_url(:anchor => "price"), class: "genric-btn primary-border small" %>
          </li>
          <li>
              <%= link_to 'Alugue uma Wanderbag!', new_subscription_url, class: 'genric-btn primary small' %>
          </li>
        </ul>
      </nav><!-- #nav-menu-container -->		    		
    </div>
  </div>
</header><!-- #header -->	

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="zxx" class="no-js">

  <body>
    <!-- start banner Area -->
    <section class="banner-area" id="home">	
      <div class="container">
        <div class="row fullscreen d-flex align-items-center justify-content-center">
          <div class="banner-content col-lg-7">
            <h1>
              Alugue aqui a sua WanderBag!
            </h1>
            <p class="pt-20 pb-20">
              Gaste mais com a sua viagem e não com a compra de malas para depois deixá-las guardadas no armário até a próxima viagem.
            </p>
          </div>											
        </div>
      </div>
    </section>
    <!-- End banner Area -->	

    <!-- Start we-offer Area -->
    <section class="we-offer-area section-gap" id="offer">
      <div class="container">
        <div class="row d-flex justify-content-center">
          <div class="menu-content pb-60 col-lg-10">
            <div class="title text-center">
              <h1 class="mb-10">Nossos serviços</h1>
              <p>É pratico, simples e seguro. Tudo para a comodidade de sua viagem.</p>
            </div>
          </div>
        </div>						
        <div class="row">
          <div class="col-lg-6">
            <div class="single-offer d-flex flex-row pb-30">
              <div class="icon">
                <img src="/template/img/s1.png" alt="">
              </div>
              <div class="desc">
                <a href="#"><h4>Diversos modelos e tamanho</h4></a>
                <p>
                  Possuimos uma variedade de modelos e tamanho de malas. Cada uma delas com um estilo e identidade diferente, tudo para se encaixar perfeitamente com suas necessidades!
                </p>
              </div>
            </div>
            <div class="single-offer d-flex flex-row pb-30">
              <div class="icon">
                <img src="/template/img/s3.png" alt="">
              </div>
              <div class="desc">
                <a href="#"><h4>Suporte e atendimento quando e onde estiver</h4></a>
                <p>
                  Disponibilidade de atendimento e socorro em caso de problemas com sua WanderBag 24 horas por dia, 7 dias na semana. Para que você possa viajar tranquilo, e não esquentar a cabeça caso ocorra algum imprevisto!
                </p>
              </div>
            </div>
          </div>
          <div class="col-lg-6">
            <div class="single-offer d-flex flex-row pb-30">
              <div class="icon">
                <img src="/template/img/s2.png" alt="">
              </div>
              <div class="desc">
                <a href="#"><h4>Seguro</h4></a>
                <p>
                  Oferecemos também, seguro para sua bagagem e para a WanderBag alugada. Adquirir esse serviço, é sinônimo de viagem tranquila!
                </p>
              </div>
            </div>
            <div class="single-offer d-flex flex-row pb-30">
              <div class="icon">
                <img src="/template/img/s4.png" alt="">
              </div>
              <div class="desc">
                <a href="#"><h4>Entregas</h4></a>
                <p>
                  Está sem tempo para retirar ou devolver sua WanderBag? Sem problemas, entregamos ela onde você preferir!
                </p>
              </div>
            </div>
          </div>												
        </div>
      </div>	
    </section>
    <!-- End we-offer Area -->
    

    <!-- Start home-video Area -->
    <section class="home-video-area" id="about">
      <div class="container-fluid">
        <div class="row justify-content-end align-items-center">
          <div class="col-lg-4 no-padding video-right">
            <p class="top-title">Entenda as vantagens</p>
            <h1>PRATICIDADE<br>
            ECONOMIA<br>
            GANHO DE ESPAÇO</h1>
            <p><span>Porque alugar é a melhor opção?</span></p>
            <p>
              Deixe de consumir espaço no seu armário com uma mala que fica a maior parte do ano sem uso, e ainda pague menos para usufruir de uma mala de altíssima qualidade e perfeito estado de conservação. Isso lhe permitirá fazer bom uso dos grandes espaços que irá ficar disponíveis no seu armário.
            </p>
          </div>
          <section class="video-area col-lg-6">
            <div class="overlay overlay-bg"></div>
            <div class="container">
              <div class="video-content">
                <a href="https://www.youtube.com/watch?v=wT100KMlxBw" class="play-btn"><img src="/template/img/play-btn.png" alt=""></a>
              </div>
            </div>
          </section>											
        </div>
      </div>	
    </section>
    <!-- End home-aboutus Area -->


    <!-- Start home-aboutus Area -->
    <section class="home-aboutus-area">
      <div class="container-fluid">
        <div class="row justify-content-center align-items-center">
          <div class="col-lg-8 no-padding about-left">
            <img class="img-fluid" src="/template/img/about-bg.jpg" alt="">
          </div>
          <div class="col-lg-4 no-padding about-right">
            <p class="top-title">Especialistas para melhor atendê-lo</p>
            <h1 class="text-white">Equipe de suporte <br>
            Corretor de seguros</h1>
            <p><span>Nossa equipe está sempre preparada para te ajudar a ter uma viagem tranquila e sem dores de cabeça!</span></p>
            <p>
              Suporte e corretor de seguros 24 horas por dia, durante toda a semana, apta a tirar dúvidas, e resolver qualquer casualidade que possa vir a ocorrer com nossos serviços enquanto você desfruta prazerosamente sua viagem!
            </p>
          </div>
        </div>
      </div>	
    </section>
    <!-- End home-aboutus Area -->

    <!-- Start testomial Area -->
    <section class="testomial-area section-gap" id="wanderbags">
      <div class="container">
        <div class="row d-flex justify-content-center">
          <div class="menu-content pb-60 col-lg-10">
            <div class="title text-center">
              <h1 class="mb-10">Alguns de nossos modelos de WanderBag!</h1>
              <p>É com prazer que lhe damos a oportunidade de aprenciar alguns de nossos maravilhosos modelos de WanderBag! E isso é só o começo.</p>
            </div>
          </div>
        </div>						
        <div class="row">
          <div class="active-tstimonial-carusel">
            <div class="single-testimonial item">
              <img class="image img-fluid" src="/template/img/p1.jpg" alt="">
              <a href="/template/img/p1.jpg" class="img-pop-up">	
                <div class="middle">
                  <div class="text"><span class="lnr lnr-frame-expand"></span></div>
                </div>
              </a>
            </div>
            <div class="single-testimonial item">
              <img class="image img-fluid" src="/template/img/p2.jpg" alt="">
              <a href="/template/img/p2.jpg" class="img-pop-up">	
                <div class="middle">
                  <div class="text"><span class="lnr lnr-frame-expand"></span></div>
                </div>
              </a>
            </div>
            <div class="single-testimonial item">
              <img class="image img-fluid" src="/template/img/p3.jpg" alt="">
              <a href="/template/img/p3.jpg" class="img-pop-up">	
                <div class="middle">
                  <div class="text"><span class="lnr lnr-frame-expand"></span></div>
                </div>
              </a>
            </div>
            <div class="single-testimonial item">
              <img class="image img-fluid" src="/template/img/p4.jpg" alt="">
              <a href="/template/img/p4.jpg" class="img-pop-up">	
                <div class="middle">
                  <div class="text"><span class="lnr lnr-frame-expand"></span></div>
                </div>
              </a>
            </div>
          </div>
        </div>
      </div>	
    </section>
    <!-- End testomial Area -->    
  
    <!-- Start price Area -->
    <section class="price-area section-gap" id="price">
      <div class="container">
        <div class="row d-flex justify-content-center">
          <div class="menu-content pb-60 col-lg-8">
            <div class="title text-center">
              <h1 class="mb-10">Modelos de WanderBag conforme sua necessidade!</h1>
              <p>E o melhor: cabe no seu bolso.</p>
            </div>
          </div>
        </div>					
        <div class="row">
          <div class="col-lg-4">
            <div class="single-price">
              <div class="top-sec d-flex justify-content-between">
                <div class="top-left">
                  <h4>Basic</h4>
                  <p>Para viagens de curta duração.</p>
                </div>
                <div class="top-right">
                  <h1>R$9/dia</h1>
                </div>
              </div>
              <div class="bottom-sec">
                <p>
                  1un. WanderBag! pequena
                </p>
              </div>
              <div class="end-sec">
                <ul>
                  <li>Modelos básicos e de tamanho pequeno, porém robustos</li>
                  <li>Possibilidade de adquirir seguros</li>
                  <li>Possibilidade de entrega à domícilio</li>
                  <li>Suporte 24 horas / 7 dias</li>
                </ul>
                <%# <button class="primary-btn price-btn mt-20">Purchase Plan</button> %>
              </div>								
            </div> 
          </div>
          <div class="col-lg-4">
            <div class="single-price">
              <div class="top-sec d-flex justify-content-between">
                <div class="top-left">
                  <h4>Standard</h4>
                  <p>Viagens de até 4 semanas.</p>
                </div>
                <div class="top-right">
                  <h1>R$19/dia</h1>
                </div>
              </div>
              <div class="bottom-sec">
                <p>
                  1un. WanderBag! média
                </p>
              </div>
              <div class="end-sec">
                <ul>
                  <li>Modelos intermediários e de tamanho médio, espaçosos e elegantes</li>
                  <li>Possibilidade de adquirir seguros</li>
                  <li>Entrega à domícilio</li>
                  <li>Suporte 24 horas / 7 dias</li>
                </ul>
                <%# <button class="primary-btn price-btn mt-20">Purchase Plan</button> %>
              </div>								
            </div> 
          </div>	
          <div class="col-lg-4">
            <div class="single-price">
              <div class="top-sec d-flex justify-content-between">
                <div class="top-left">
                  <h4>Premium</h4>
                  <p>Viagens superiores a 4 semanas.</p>
                </div>
                <div class="top-right">
                  <h1>R$24/dia</h1>
                </div>
              </div>
              <div class="bottom-sec">
                <p>
                  1un. WanderBag! grande
                </p>
              </div>
              <div class="end-sec">
                <ul>
                  <li>Modelos premium! De tamanho grande, modernas, espaçosas, elegantes e robustas!</li>
                  <li>Seguro incluso</li>
                  <li>Entrega à domícilio</li>
                  <li>Suporte 24 horas / 7 dias</li>
                </ul>
                <%# <button class="primary-btn price-btn mt-20">Purchase Plan</button> %>
              </div>								
            </div> 
          </div>
          <div class="menu-content mt-10 offset-lg-2 col-lg-8">
            <div class="title text-center">
              <button class="genric-btn primary arrow"><%= link_to 'ALUGUE UMA WANDERBAG!', new_subscription_url %><span class="lnr lnr-arrow-right"></span></button>
            </div>
          </div>                                        
        </div>	
      </div>
    </section>
    <!-- End price Area -->
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>Wanderbag</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicon-->
    <link rel="shortcut icon" href="/template/img/fav.png">
    <!-- Author Meta -->
    <meta name="author" content="codepixer">
    <!-- Meta Description -->
    <meta name="description" content="">
    <!-- Meta Keyword -->
    <meta name="keywords" content="">
    <!-- meta character set -->
    <meta charset="UTF-8">
    <!-- Site Title -->

    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet"> 
    <!--CSS============================================= -->
    <link rel="stylesheet" href="/template/css/linearicons.css">
    <link rel="stylesheet" href="/template/css/font-awesome.min.css">
    <link rel="stylesheet" href="/template/css/bootstrap.css">
    <link rel="stylesheet" href="/template/css/magnific-popup.css">
    <link rel="stylesheet" href="/template/css/nice-select.css">					
    <link rel="stylesheet" href="/template/css/animate.min.css">
    <link rel="stylesheet" href="/template/css/owl.carousel.css">
    <link rel="stylesheet" href="/template/css/main.css">
  </head>


  <body>
    <%= render 'header' %>
    <%= yield %>
    <%= render 'footer' %>

    <script src="/template/js/jquery-2.2.4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="/template/js/bootstrap.min.js"></script>			
    <script src="/template/js/easing.min.js"></script>			
    <script src="/template/js/hoverIntent.js"></script>
    <script src="/template/js/superfish.min.js"></script>	
    <script src="/template/js/jquery.ajaxchimp.min.js"></script>
    <script src="/template/js/jquery.magnific-popup.min.js"></script>	
    <script src="/template/js/owl.carousel.min.js"></script>			
    <script src="/template/js/jquery.sticky.js"></script>
    <script src="/template/js/jquery.nice-select.min.js"></script>			
    <script src="/template/js/parallax.min.js"></script>		
    <script src="/template/js/mail-script.js"></script>	
    <script src="/template/js/main.js"></script>
    <script>
      $( document ).ready(function() {
          <% if notice %>
              notice = <%= raw notice.to_json %>
              if (notice != "") {
                  sweetAlert(notice);
                  notice = "";
              }
          <% end %>
      })
    </script>
  </body>
</html>

app/views/subscriptions/_form.html.erb
<div class="section-top-border">
  <div class=container>
    <div class="row d-flex align-items-center justify-content-center">
      <div class="offset-lg-2 col-lg-8 col-md-8">
        <h3 class="mb-30">Formulário</h3>
          <%= form_with(model: subscription, local: true) do |form| %>
            <% if subscription.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>

                <ul>
                <% subscription.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            <% end %>

            <div class="mt-10">
              <div class="switch-wrap d-flex justify-content-between">
                <%= form.label 'Nome' %>
                <div class="input-group-icon">
                  <div class="icon"><i class="fa fa-user-circle-o" aria-hidden="true"></i></div>
                  <%= form.text_field :name, id: :subscription_name, placeholder: "Renato Baptista", class: "single-input" %>
                </div>
              </div>
            </div>
            <div class="mt-10">
              <div class="switch-wrap d-flex justify-content-between">
                <%= form.label 'E-Mail' %>
                <div class="input-group-icon">
                  <div class="icon"><i class="fa fa-envelope-o" aria-hidden="true"></i></div>
                  <%= form.text_field :email, id: :subscription_email, placeholder: "renato.baptista@example.com", class: "single-input" %>
                </div>
              </div>
            </div>
            <div class="mt-10">
              <div class="switch-wrap d-flex justify-content-between">
                <%= form.label 'Data Retirada' %>
                <div class="input-group-icon">
                  <div class="icon"><i class="fa fa-calendar-o" aria-hidden="true"></i></div>
                  <%= form.text_field :initial_date, id: :subscription_initial_date, placeholder: "Data Retirada: DD/MM/AAAA", class: "single-input" %>
                </div>
              </div>
            </div>
            <div class="mt-10">
              <div class="switch-wrap d-flex justify-content-between">
                <%= form.label 'Data Devolução' %>
                <div class="input-group-icon">
                  <div class="icon"><i class="fa fa-calendar-o" aria-hidden="true"></i></div>
                  <%= form.text_field :final_date, id: :subscription_final_date, placeholder: "Data Devolução: DD/MM/AAAA", class: "single-input" %>
                </div>
              </div>
            </div>
            <div class="mt-10">
            <div class="switch-wrap d-flex justify-content-between">
                <%= form.label 'Mochila(s) Pequena(s)' %>
                <div class="input-group-icon">
                  <div class="icon"><i class="fa fa-shopping-bag" aria-hidden="true"></i></div>
                  <%= form.number_field :smallbag_quantity, id: :subscription_smallbag_quantity, placeholder: "1", class: "single-input" %>
                </div>
              </div>
            </div>
            <div class="mt-10">
              <div class="switch-wrap d-flex justify-content-between">
                <%= form.label 'Mochila(s) Média(s)' %>
                <div class="input-group-icon">
                  <div class="icon"><i class="fa fa-briefcase" aria-hidden="true"></i></div>
                  <%= form.number_field :mediumbag_quantity, id: :subscription_mediumbag_quantity, placeholder: "1", class: "single-input" %>
                </div>
              </div>
            </div>
            <div class="mt-10">
              <div class="switch-wrap d-flex justify-content-between">
                <%= form.label 'Mochila(s) Grande(s)' %>
                <div class="input-group-icon">
                  <div class="icon"><i class="fa fa-suitcase" aria-hidden="true"></i></div>
                  <%= form.number_field :bigbag_quantity, id: :subscription_bigbag_quantity, placeholder: "1", class: "single-input" %>
                </div>
              </div>
            </div>
            <div class="mt-10">
              <div class="switch-wrap d-flex justify-content-between">
                <%= form.label 'Valor Total' %>
                <div class="input-group-icon">
                  <div class="icon"><i class="fa fa-money" aria-hidden="true"></i></div>
                  <%= form.text_field :value, id: :subscription_value, placeholder: "R$ 65,00", class: "single-input" %>
                </div>
              </div>
            </div>
            <div class="mt-10">
              <div class="switch-wrap d-flex justify-content-between">
                <%= form.label 'Nº Telefone' %>
                <div class="input-group-icon">
                  <div class="icon"><i class="fa fa-mobile" aria-hidden="true"></i></div>
                  <%= form.number_field :phone_number, id: :subscription_phone_number, placeholder: "(41) 3333-3333", class: "single-input" %>
                </div>
              </div>
            </div>
          </div>
          <div class="col-lg-2 col-md-2">
          </div>
          <div class="actions">
            <div class="button-group-area mt-40">
              <%= form.submit class: "genric-btn success circle", value: "Confirmar Cadastro!"%>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/subscriptions/edit.html.erb
<h1>Editing Subscription</h1>

<%= render 'form', subscription: @subscription %>

<%= link_to 'Show', @subscription %> |
<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subscriptions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Initial date</th>
      <th>Final date</th>
      <th>Smallbag quantity</th>
      <th>Mediumbag quantity</th>
      <th>Bigbag quantity</th>
      <th>Value</th>
      <th>Phone number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subscriptions.each do |subscription| %>
      <tr>
        <td><%= subscription.name %></td>
        <td><%= subscription.email %></td>
        <td><%= subscription.initial_date %></td>
        <td><%= subscription.final_date %></td>
        <td><%= subscription.smallbag_quantity %></td>
        <td><%= subscription.mediumbag_quantity %></td>
        <td><%= subscription.bigbag_quantity %></td>
        <td><%= subscription.value %></td>
        <td><%= subscription.phone_number %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subscription', new_subscription_path %>

app/views/subscriptions/new.html.erb
<section class="sample-text-area">
  <div class="container">
    <div class="row d-flex align-items-center justify-content-center">
      <div class="col-lg-8">
        <h3 class="text-heading">Gratidão</h3>
        <p class="sample-text">
          Ficamos muito contentes em saber que as pessoas tem interesse em nosso produto! Ao apoiar nossa causa, e realizar a inscrição para receber novidades, você tornará mais fácil nosso planejamento, e fará com que nossos serviços estejam disponíveis o mais rápido possível para melhor atendê-lo.<br> 
        </p>
      </div>
    </div>
  </div>
</section>

<%= render 'form', subscription: @subscription %>

app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @subscription.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @subscription.email %>
</p>

<p>
  <strong>Initial date:</strong>
  <%= @subscription.initial_date %>
</p>

<p>
  <strong>Final date:</strong>
  <%= @subscription.final_date %>
</p>

<p>
  <strong>Smallbag quantity:</strong>
  <%= @subscription.smallbag_quantity %>
</p>

<p>
  <strong>Mediumbag quantity:</strong>
  <%= @subscription.mediumbag_quantity %>
</p>

<p>
  <strong>Bigbag quantity:</strong>
  <%= @subscription.bigbag_quantity %>
</p>

<p>
  <strong>Value:</strong>
  <%= @subscription.value %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @subscription.phone_number %>
</p>

<%= link_to 'Edit', edit_subscription_path(@subscription) %> |
<%= link_to 'Back', subscriptions_path %>